version: "0.1"

x-common-variables: &common-variables
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

services:
  endpoint:
    image: openjdk:8-jre-alpine
    environment: *common-variables
    ports:
      - "80:8080"
    volumes:
      - ./ppr-endpoint/target/ppr-endpoint-0.0.1-SNAPSHOT.jar:/ppr-endpoint.jar
    command: ["java", "-jar", "ppr-endpoint.jar"]
    depends_on:
      pg-database:
        condition: service_healthy
  pg-database:
    image: postgres:14
    environment: *common-variables
    ports:
      - "5433:5432"
    volumes:
      - ./db-backups/backup.sql:/docker-entrypoint-initdb.d/backup.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  pg-admin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    profiles: ["local"]
