version: "0.1"
services:
  pg-database:
    image: postgres:14
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./sql/backup.sql:/docker-entrypoint-initdb.d/backup.sql
